language: c
env:
    - OCAML_VERSION=4.08
before_install:
    - curl -L https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh | sh
    - eval $(opam config env)
script:
    - bash test.sh

